// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itgmfywhkvywttiysnfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0Z21meXdoa3Z5d3R0aXlzbmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDYzNDQsImV4cCI6MjA2NDk4MjM0NH0._0-AbDs63ZF62TYczg1cS5lNvuVcEufjTQhC_89Kfj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);